openapi: 3.0.0
info:
  title: Write
  version: '1.0'
  description: ''
servers:
  - url: 'https://api.danim.com'
paths:
  /write/video/create:
    post:
      summary: "\U0001F4BF Create a video \U0001F37C"
      operationId: post-write-video-generate
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - description: x-data
                    properties:
                      id:
                        type: string
                        description: Video ID
                      short_id:
                        type: string
                        description: 'Video short ID (i.e. which appears publicly in several URLs, such as the player’s one)'
                      name:
                        type: string
                        description: Video name
                  - description: x-errors
                    properties:
                      FileIsTooLarge:
                        type: string
                        description: One provided file size is too high
                      FileExtensionTypeIsNotAccepted:
                        type: string
                        description: 'One provided file extension is not authorized (in general, on the platform)'
                      FileMimeTypeIsNotAccepted:
                        type: string
                        description: 'One provided file MIME type is not authorized (in general, on the platform)'
                      TemplateDataFileNotFound:
                        type: string
                        description: 'One provided file ID has been provided but cannot be found in old previous data (e.g. a preloaded-file ID has been provided, but was expired, so that we try to find the ID in old data files, with no success)'
                      InvalidTemplateDataFileFormat:
                        type: string
                        description: One provided file format is not valid.
                      InvalidTemplateDataFileMimeType:
                        type: string
                        description: One provided file MIME type does not correspond to its expected type (e.g. if you provide a mp4 when the input should be an image)
                      MissingTemplateDataComposition:
                        type: string
                        description: 'A required template composition has not been provided in `template_data`, when it should have been (see the [important notice above](#_write_video_create_required-and-optional-compos-and-inputs))'
                      MissingTemplateDataInput:
                        type: string
                        description: 'A required template input has not been provided in `template_data`, when it should have been (see the [important notice above](#_write_video_create_required-and-optional-compos-and-inputs))'
                      WorkspaceNotFound:
                        type: string
                        description: The workspace cannot be found
                      TemplateNotFound:
                        type: string
                        description: The template cannot be found
                      WorkspaceInconsistency:
                        type: string
                        description: When workspace does not match with template’s one
                      OrganizationInconsistency:
                        type: string
                        description: When workspace organization does not match with template’s one
                      PlanIsInsufficientForGeneration:
                        type: string
                        description: The plan is not adapted (e.g. “FREE”)
                      InsufficientCreditsForGeneration:
                        type: string
                        description: The plan is adapted but no sufficient credits left
                type: object
              examples:
                'Example #1: minimalistic':
                  value:
                    success: true
                    data:
                      id: cad06342-b853-4e19-8bc9-52f6b613a7b0
                      short_id: jhads673h
                      name: 'One video #jhads673h'
                'Example #2: mistake':
                  value:
                    success: false
                    message: The input "B1" is required but has not been provided
                    meta:
                      type: MissingTemplateDataInput
                'Example #3: with a file':
                  value:
                    success: true
                    data:
                      id: 80d4139f-1182-4c5b-bd8e-3a00595e08af
                      short_id: fg56h378k
                      name: Alice's video
        '':
          description: ''
      description: 'This endpoint lets you create a video from scratch. You may choose to set it as draft, or directly launch it for generation.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                template_id:
                  type: string
                  description: ID of template from which the video must be generated
                template_data:
                  type:
                    - object
                    - string
                  description: 'Template data for generation (_id/value pairs: see examples [below](#_write_video_create_examples)). If there’s no file (URL, ID, bin, etc.) in your data, you can provide a JSON-encoded string.'
                description:
                  default: 'null'
                  type:
                    - string
                    - 'null'
                  description: Description of the video
                name:
                  type:
                    - string
                    - 'null'
                  default: 'Generated (template name + ‘ #’ + short ID)'
                  description: Name of the video
                workspace_id:
                  type:
                    - string
                    - 'null'
                  default: Will be the first of template’s organization (if it exists)
                  description: Workspace in which the video should be created
                callback_url:
                  type:
                    - string
                    - 'null'
                  description: |-
                    This webhook URL will be sollicitated on video generation success.
                    It will by default use `POST` method, and provide the following parameters:
                    * `id` (video ID)
                    * `raw_url` (video cloud raw URL)
                    * `player_url` (link for video play - e.g. iframe).

                    If you prefer to get this stuff done via the `GET` method, just add `+get` in your url scheme (e.g. `https+get://my.app/webhook/1`)
                  default: 'null'
              required:
                - template_id
                - template_data
            examples:
              'Example #1: minimalistic':
                value:
                  template_id: 967702d6-eb8a-4734-a398-4f3c10359d95
                  template_data:
                    A1: Bob's select value
              'Example #2: mistake':
                value:
                  template_id: 967702d6-eb8a-4734-a398-4f3c10359d95
                  template_data:
                    A1: Bob's select value
                    B3: Bob's text value
              'Example #3: with a file':
                value:
                  template_id: 967702d6-eb8a-4734-a398-4f3c10359d95
                  template_data:
                    A1: Alice's select value
                    B1: Alice's text value
                    B2: www-xxx-yyy-zzz
                  name: Alice's video
                  description: 'Hi everyone, this video has an image! Alice.'
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
        description: '$ref:#_write_video_create_required-and-optional-compos-and-inputs'
      tags:
        - public
        - '#_write_video_create'
    parameters: []
  /write/video/change:
    post:
      summary: "\U0001F4BF Change a video \U0001F58D"
      operationId: post-write-video-change
      responses:
        '200':
          description: ''
      tags:
        - public
        - '#_write_video_change'
      description: 'This endpoint lets you change your video: name, description, etc.'
    parameters: []
  /write/video/remove:
    parameters: []
    post:
      summary: "\U0001F4BF Remove a video \U0001F5D1"
      operationId: post-write-video-remove
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - description: x-data
                  - description: x-errors
                    properties:
                      VideoHasAlreadyBeenRemoved:
                        type: string
                        description: The video has already been removed
                      VideoNotFound:
                        type: string
                        description: The video cannot be found
                type: object
      description: This endpoint lets you remove one of your videos.
      parameters: []
      tags:
        - public
        - '#_write_video_remove'
  /write/video/generate:
    post:
      summary: "\U0001F4BF Generate a video \U0001F680"
      tags: []
      responses: {}
      operationId: post-write-video-generate
      description: This endpoint lets you launch your draft video generation.
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: public
  - name: '#_write_video_create'
  - name: '#_write_video_change'
  - name: '#_write_video_remove'
